### PR TITLE
Clean up for posting to STLRUG repo

### PR DESCRIPTION
**Pull request by ryapric**
Here's all the material from the workshop, Josh. I tried to submit a cleaner version of everything, but haven't added tests. I can add those later in a separate PR.

Thanks!

### CODE REVIEW

**Comment by joshuaulrich** [comment]
Thanks Ryan! It looks like this is only the package.  Can you also add your slides?  If so, it might make sense to move the package code to a new directory.

**Comment by ryapric** [comment]
I've got the slides linked in the README, since it's a Google Doc. Would
you rather it be a separate file?

**Comment by joshuaulrich** [comment]
It would be nice if it were a PDF.  Most of the other months contain a presentation file, and it would be nice if this repo is self-contained.

**Comment by ryapric** [comment]
Sure, makes sense. I added the presentation as PDF, moved the package one level down, updated the README to suggest the static doc, and got around to adding some tests. Let me know if there's anything else you think should change.

**Comment by joshuaulrich** [comment]
Awesome, thank you!  I just added a readme (same as your meetup description) with links to the relevant packages and tools.  Thanks again for presenting!

**Pull request merged**
